package com.sgg.hibernate;

// Generated Jun 17, 2011 6:49:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Account generated by hbm2java
 */
@Entity
@Table(name = "account")
public class Account implements java.io.Serializable {

	private Integer id;
	private String accountName;
	private String accountFirstName;
	private String accountLastName;
	private int accountContactInfoId;
	private Date createDate;
	private Date updateDate;
	private Boolean active;
	private Boolean deleted;
	private Date deleteDate;

	public Account() {
	}

	public Account(int accountContactInfoId) {
		this.accountContactInfoId = accountContactInfoId;
	}

	public Account(String accountName, String accountFirstName,
			String accountLastName, int accountContactInfoId, Date createDate,
			Date updateDate, Boolean active, Boolean deleted, Date deleteDate) {
		this.accountName = accountName;
		this.accountFirstName = accountFirstName;
		this.accountLastName = accountLastName;
		this.accountContactInfoId = accountContactInfoId;
		this.createDate = createDate;
		this.updateDate = updateDate;
		this.active = active;
		this.deleted = deleted;
		this.deleteDate = deleteDate;
	}

	@SequenceGenerator(name = "generator", sequenceName = "account_id_seq")
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "account_name", length = 100)
	public String getAccountName() {
		return this.accountName;
	}

	public void setAccountName(String accountName) {
		this.accountName = accountName;
	}

	@Column(name = "account_first_name", length = 40)
	public String getAccountFirstName() {
		return this.accountFirstName;
	}

	public void setAccountFirstName(String accountFirstName) {
		this.accountFirstName = accountFirstName;
	}

	@Column(name = "account_last_name", length = 75)
	public String getAccountLastName() {
		return this.accountLastName;
	}

	public void setAccountLastName(String accountLastName) {
		this.accountLastName = accountLastName;
	}

	@Column(name = "account_contact_info_id", nullable = false)
	public int getAccountContactInfoId() {
		return this.accountContactInfoId;
	}

	public void setAccountContactInfoId(int accountContactInfoId) {
		this.accountContactInfoId = accountContactInfoId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 35)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", length = 35)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Column(name = "active")
	public Boolean getActive() {
		return this.active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	@Column(name = "deleted")
	public Boolean getDeleted() {
		return this.deleted;
	}

	public void setDeleted(Boolean deleted) {
		this.deleted = deleted;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "delete_date", length = 35)
	public Date getDeleteDate() {
		return this.deleteDate;
	}

	public void setDeleteDate(Date deleteDate) {
		this.deleteDate = deleteDate;
	}

}
