package com.sgg.hibernate;

// Generated Jun 17, 2011 6:49:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ContactInfo generated by hbm2java
 */
@Entity
@Table(name = "contact_info")
public class ContactInfo implements java.io.Serializable {

	private Integer id;
	private String contactInfoLine1;
	private String contactInfoLine2;
	private String contactInfoLine3;
	private String contactInfoLine4;
	private String contactInfoLine5;
	private String contactInfoCity;
	private String contactInfoState;
	private String contactInfoZip;
	private String contactInfoDescription;
	private String contactInfoPhone;
	private String contactInfoPhone2;
	private String contactInfoPhone3;
	private String contactInfoEmail;
	private String contactInfoEmail2;
	private int contactInfoSeq;
	private Date updateDate;
	private Date createDate;
	private Boolean active;
	private Boolean deleted;
	private Date deleteDate;

	public ContactInfo() {
	}

	public ContactInfo(int contactInfoSeq) {
		this.contactInfoSeq = contactInfoSeq;
	}

	public ContactInfo(String contactInfoLine1, String contactInfoLine2,
			String contactInfoLine3, String contactInfoLine4,
			String contactInfoLine5, String contactInfoCity,
			String contactInfoState, String contactInfoZip,
			String contactInfoDescription, String contactInfoPhone,
			String contactInfoPhone2, String contactInfoPhone3,
			String contactInfoEmail, String contactInfoEmail2,
			int contactInfoSeq, Date updateDate, Date createDate,
			Boolean active, Boolean deleted, Date deleteDate) {
		this.contactInfoLine1 = contactInfoLine1;
		this.contactInfoLine2 = contactInfoLine2;
		this.contactInfoLine3 = contactInfoLine3;
		this.contactInfoLine4 = contactInfoLine4;
		this.contactInfoLine5 = contactInfoLine5;
		this.contactInfoCity = contactInfoCity;
		this.contactInfoState = contactInfoState;
		this.contactInfoZip = contactInfoZip;
		this.contactInfoDescription = contactInfoDescription;
		this.contactInfoPhone = contactInfoPhone;
		this.contactInfoPhone2 = contactInfoPhone2;
		this.contactInfoPhone3 = contactInfoPhone3;
		this.contactInfoEmail = contactInfoEmail;
		this.contactInfoEmail2 = contactInfoEmail2;
		this.contactInfoSeq = contactInfoSeq;
		this.updateDate = updateDate;
		this.createDate = createDate;
		this.active = active;
		this.deleted = deleted;
		this.deleteDate = deleteDate;
	}

	@SequenceGenerator(name = "generator", sequenceName = "contact_info_id_seq")
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "contact_info_line1", length = 100)
	public String getContactInfoLine1() {
		return this.contactInfoLine1;
	}

	public void setContactInfoLine1(String contactInfoLine1) {
		this.contactInfoLine1 = contactInfoLine1;
	}

	@Column(name = "contact_info_line2", length = 100)
	public String getContactInfoLine2() {
		return this.contactInfoLine2;
	}

	public void setContactInfoLine2(String contactInfoLine2) {
		this.contactInfoLine2 = contactInfoLine2;
	}

	@Column(name = "contact_info_line3", length = 100)
	public String getContactInfoLine3() {
		return this.contactInfoLine3;
	}

	public void setContactInfoLine3(String contactInfoLine3) {
		this.contactInfoLine3 = contactInfoLine3;
	}

	@Column(name = "contact_info_line4", length = 100)
	public String getContactInfoLine4() {
		return this.contactInfoLine4;
	}

	public void setContactInfoLine4(String contactInfoLine4) {
		this.contactInfoLine4 = contactInfoLine4;
	}

	@Column(name = "contact_info_line5", length = 100)
	public String getContactInfoLine5() {
		return this.contactInfoLine5;
	}

	public void setContactInfoLine5(String contactInfoLine5) {
		this.contactInfoLine5 = contactInfoLine5;
	}

	@Column(name = "contact_info_city", length = 50)
	public String getContactInfoCity() {
		return this.contactInfoCity;
	}

	public void setContactInfoCity(String contactInfoCity) {
		this.contactInfoCity = contactInfoCity;
	}

	@Column(name = "contact_info_state", length = 2)
	public String getContactInfoState() {
		return this.contactInfoState;
	}

	public void setContactInfoState(String contactInfoState) {
		this.contactInfoState = contactInfoState;
	}

	@Column(name = "contact_info_zip", length = 10)
	public String getContactInfoZip() {
		return this.contactInfoZip;
	}

	public void setContactInfoZip(String contactInfoZip) {
		this.contactInfoZip = contactInfoZip;
	}

	@Column(name = "contact_info_description", length = 25)
	public String getContactInfoDescription() {
		return this.contactInfoDescription;
	}

	public void setContactInfoDescription(String contactInfoDescription) {
		this.contactInfoDescription = contactInfoDescription;
	}

	@Column(name = "contact_info_phone", length = 20)
	public String getContactInfoPhone() {
		return this.contactInfoPhone;
	}

	public void setContactInfoPhone(String contactInfoPhone) {
		this.contactInfoPhone = contactInfoPhone;
	}

	@Column(name = "contact_info_phone2", length = 20)
	public String getContactInfoPhone2() {
		return this.contactInfoPhone2;
	}

	public void setContactInfoPhone2(String contactInfoPhone2) {
		this.contactInfoPhone2 = contactInfoPhone2;
	}

	@Column(name = "contact_info_phone3", length = 20)
	public String getContactInfoPhone3() {
		return this.contactInfoPhone3;
	}

	public void setContactInfoPhone3(String contactInfoPhone3) {
		this.contactInfoPhone3 = contactInfoPhone3;
	}

	@Column(name = "contact_info_email", length = 100)
	public String getContactInfoEmail() {
		return this.contactInfoEmail;
	}

	public void setContactInfoEmail(String contactInfoEmail) {
		this.contactInfoEmail = contactInfoEmail;
	}

	@Column(name = "contact_info_email2", length = 100)
	public String getContactInfoEmail2() {
		return this.contactInfoEmail2;
	}

	public void setContactInfoEmail2(String contactInfoEmail2) {
		this.contactInfoEmail2 = contactInfoEmail2;
	}

	@Column(name = "contact_info_seq", nullable = false)
	public int getContactInfoSeq() {
		return this.contactInfoSeq;
	}

	public void setContactInfoSeq(int contactInfoSeq) {
		this.contactInfoSeq = contactInfoSeq;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", length = 35)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 35)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "active")
	public Boolean getActive() {
		return this.active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	@Column(name = "deleted")
	public Boolean getDeleted() {
		return this.deleted;
	}

	public void setDeleted(Boolean deleted) {
		this.deleted = deleted;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "delete_date", length = 35)
	public Date getDeleteDate() {
		return this.deleteDate;
	}

	public void setDeleteDate(Date deleteDate) {
		this.deleteDate = deleteDate;
	}

}
