package com.sgg.hibernate;

// Generated Jun 17, 2011 6:49:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Convo generated by hbm2java
 */
@Entity
@Table(name = "convo")
public class Convo implements java.io.Serializable {

	private Integer id;
	private String convoType;
	private Integer originalLinkId;
	private String shortDescription;
	private String longDescription;
	private Integer creatorUserId;
	private Integer lastContributedUserId;
	private Date updateDate;
	private Date createDate;
	private Boolean active;
	private Boolean deleted;
	private Date deleteDate;

	public Convo() {
	}

	public Convo(String convoType) {
		this.convoType = convoType;
	}

	public Convo(String convoType, Integer originalLinkId,
			String shortDescription, String longDescription,
			Integer creatorUserId, Integer lastContributedUserId,
			Date updateDate, Date createDate, Boolean active, Boolean deleted,
			Date deleteDate) {
		this.convoType = convoType;
		this.originalLinkId = originalLinkId;
		this.shortDescription = shortDescription;
		this.longDescription = longDescription;
		this.creatorUserId = creatorUserId;
		this.lastContributedUserId = lastContributedUserId;
		this.updateDate = updateDate;
		this.createDate = createDate;
		this.active = active;
		this.deleted = deleted;
		this.deleteDate = deleteDate;
	}

	@SequenceGenerator(name = "generator", sequenceName = "convo_id_seq")
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "convo_type", nullable = false, length = 15)
	public String getConvoType() {
		return this.convoType;
	}

	public void setConvoType(String convoType) {
		this.convoType = convoType;
	}

	@Column(name = "original_link_id")
	public Integer getOriginalLinkId() {
		return this.originalLinkId;
	}

	public void setOriginalLinkId(Integer originalLinkId) {
		this.originalLinkId = originalLinkId;
	}

	@Column(name = "short_description", length = 75)
	public String getShortDescription() {
		return this.shortDescription;
	}

	public void setShortDescription(String shortDescription) {
		this.shortDescription = shortDescription;
	}

	@Column(name = "long_description", length = 1000)
	public String getLongDescription() {
		return this.longDescription;
	}

	public void setLongDescription(String longDescription) {
		this.longDescription = longDescription;
	}

	@Column(name = "creator_user_id")
	public Integer getCreatorUserId() {
		return this.creatorUserId;
	}

	public void setCreatorUserId(Integer creatorUserId) {
		this.creatorUserId = creatorUserId;
	}

	@Column(name = "last_contributed_user_id")
	public Integer getLastContributedUserId() {
		return this.lastContributedUserId;
	}

	public void setLastContributedUserId(Integer lastContributedUserId) {
		this.lastContributedUserId = lastContributedUserId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", length = 35)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 35)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "active")
	public Boolean getActive() {
		return this.active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	@Column(name = "deleted")
	public Boolean getDeleted() {
		return this.deleted;
	}

	public void setDeleted(Boolean deleted) {
		this.deleted = deleted;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "delete_date", length = 35)
	public Date getDeleteDate() {
		return this.deleteDate;
	}

	public void setDeleteDate(Date deleteDate) {
		this.deleteDate = deleteDate;
	}

}
