package com.sgg.hibernate;

// Generated Jun 17, 2011 6:49:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LinkInfo generated by hbm2java
 */
@Entity
@Table(name = "link_info")
public class LinkInfo implements java.io.Serializable {

	private Integer id;
	private String linkType;
	private String miniUrl;
	private String longUrl;
	private String internalUrl;
	private String description;
	private int userId;
	private Integer parentId;
	private Boolean crawl;
	private Date lastCrawlDate;
	private Date updateDate;
	private Date createDate;
	private Boolean active;
	private Boolean deleted;
	private Date deleteDate;

	public LinkInfo() {
	}

	public LinkInfo(String longUrl, int userId) {
		this.longUrl = longUrl;
		this.userId = userId;
	}

	public LinkInfo(String linkType, String miniUrl, String longUrl,
			String internalUrl, String description, int userId,
			Integer parentId, Boolean crawl, Date lastCrawlDate,
			Date updateDate, Date createDate, Boolean active, Boolean deleted,
			Date deleteDate) {
		this.linkType = linkType;
		this.miniUrl = miniUrl;
		this.longUrl = longUrl;
		this.internalUrl = internalUrl;
		this.description = description;
		this.userId = userId;
		this.parentId = parentId;
		this.crawl = crawl;
		this.lastCrawlDate = lastCrawlDate;
		this.updateDate = updateDate;
		this.createDate = createDate;
		this.active = active;
		this.deleted = deleted;
		this.deleteDate = deleteDate;
	}

	@SequenceGenerator(name = "generator", sequenceName = "link_info_id_seq")
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "link_type", length = 15)
	public String getLinkType() {
		return this.linkType;
	}

	public void setLinkType(String linkType) {
		this.linkType = linkType;
	}

	@Column(name = "mini_url", length = 75)
	public String getMiniUrl() {
		return this.miniUrl;
	}

	public void setMiniUrl(String miniUrl) {
		this.miniUrl = miniUrl;
	}

	@Column(name = "long_url", nullable = false, length = 10000)
	public String getLongUrl() {
		return this.longUrl;
	}

	public void setLongUrl(String longUrl) {
		this.longUrl = longUrl;
	}

	@Column(name = "internal_url", length = 10000)
	public String getInternalUrl() {
		return this.internalUrl;
	}

	public void setInternalUrl(String internalUrl) {
		this.internalUrl = internalUrl;
	}

	@Column(name = "description", length = 300)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "parent_id")
	public Integer getParentId() {
		return this.parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	@Column(name = "crawl")
	public Boolean getCrawl() {
		return this.crawl;
	}

	public void setCrawl(Boolean crawl) {
		this.crawl = crawl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_crawl_date", length = 35)
	public Date getLastCrawlDate() {
		return this.lastCrawlDate;
	}

	public void setLastCrawlDate(Date lastCrawlDate) {
		this.lastCrawlDate = lastCrawlDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", length = 35)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 35)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "active")
	public Boolean getActive() {
		return this.active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	@Column(name = "deleted")
	public Boolean getDeleted() {
		return this.deleted;
	}

	public void setDeleted(Boolean deleted) {
		this.deleted = deleted;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "delete_date", length = 35)
	public Date getDeleteDate() {
		return this.deleteDate;
	}

	public void setDeleteDate(Date deleteDate) {
		this.deleteDate = deleteDate;
	}

}
