package com.sgg.hibernate;

// Generated Jun 14, 2011 11:24:28 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LinkInfoId generated by hbm2java
 */
@Embeddable
public class LinkInfoId implements java.io.Serializable {

	private int id;
	private int parentId;

	public LinkInfoId() {
	}

	public LinkInfoId(int id, int parentId) {
		this.id = id;
		this.parentId = parentId;
	}

	@Column(name = "id", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "parent_id", nullable = false)
	public int getParentId() {
		return this.parentId;
	}

	public void setParentId(int parentId) {
		this.parentId = parentId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LinkInfoId))
			return false;
		LinkInfoId castOther = (LinkInfoId) other;

		return (this.getId() == castOther.getId())
				&& (this.getParentId() == castOther.getParentId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + this.getParentId();
		return result;
	}

}
